// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web {
	
	
	public partial class FrmView {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.MultiView multiView;
		
		protected System.Web.UI.WebControls.View view1;
		
		protected System.Web.UI.WebControls.View view2;
		
		protected System.Web.UI.WebControls.View view3;
		
		protected System.Web.UI.WebControls.Button btnNext;
	}
}
